feat: Add support to producer end-to-end encryption
datastax/pulsar-jms pull request #115
Opened 2023-10-25 16:29 UTC by jffp113

I added support for pulsar end-to-end encryption.

2023-10-26 09:38 UTC, HenriqueFSilva commented
Would really like for this to be implemented!

2024-04-05 09:11 UTC, eolivelli requested changes
Hello,
Can you please rebase on top of the master branch ?
CI didn't run.

We are going to cut a new release soon and your improvement is very helpful, sorry for so late reply

2024-04-05 09:11 UTC, eolivelli commented on pulsar-jms/src/main/java/com/datastax/oss/pulsar/jms/PulsarConnectionFactory.java
> +import org.apache.pulsar.client.api.*;
can you please remove this star import ?

2024-04-05 18:25 UTC, jffp113 commented
I changed the pull requesrt accordingly to your request.

2024-04-16 12:37 UTC, closed without merging