Fix for Pulsar-JMS library producer.send() method
datastax/pulsar-jms pull request #152
Opened 2024-08-16 11:34 UTC by mukesh-ctds

2024-08-20 15:52 UTC, eolivelli requested changes
I am pretty sure that this change will break some tests.

I tihnk taht the current behavior is correct.

Can you please provide more context and the reason for such modifications ?

2024-08-20 16:10 UTC, mukesh-ctds commented
I reviewed the JMS specification, and according to it, the JMSCorrelationID, JMSReplyTo, and JMSType properties should be set by the client rather than the `send` method. However, the current implementation sets these values at the producer level, not at the message level. By default, these properties on the producer object are null, so they are being set to null regardless of whether the message has values for these properties.

In short, under the current behavior, these properties are configured at the producer level, and there is no way to set them at the message level even if desired. The customer expects these values to be set at the message level.

2024-08-21 07:36 UTC, eolivelli requested changes

2024-08-21 07:36 UTC, eolivelli commented on pulsar-jms/src/main/java/com/datastax/oss/pulsar/jms/PulsarJMSProducer.java
> -    message.setJMSCorrelationIDAsBytes(correlationID);
https://jakarta.ee/specifications/messaging/3.0/apidocs/jakarta/jms/jmsproducer

> message headers set using these methods will override any message headers that have been set directly on the message

this seems to imply that it is possible to set the correlationid on the message

According to the specs I would code it this way:

if (!message.hasCorrelationId()){
 message.setJMSCorrelationIDAsBytes(correlationID);
}

2024-08-22 11:02 UTC, eolivelli approved these changes
LGTM

2024-08-22 11:03 UTC, merged